// Generated by Wrangler on Fri Jun 07 2024 14:28:43 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	CLIENT_ID: string;
	CLIENT_SECRET: string;
	REDIRECT_URI: string;
}
