#:schema node_modules/wrangler/config-schema.json

name = "oauth"
main = "src/index.ts"
compatibility_date = "2024-06-03"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

route = { pattern = "https://api.example.com/oauth/v1/*", zone_name = "example.com" }
